# Generated by Django 4.1.3 on 2022-11-17 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstParam",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                (
                    "load_m",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="载荷质量（kg）"
                    ),
                ),
                (
                    "radius",
                    models.DecimalField(
                        decimal_places=3, max_digits=4, verbose_name="半径（m）"
                    ),
                ),
                (
                    "v_con",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="速度约束（m/s）"
                    ),
                ),
                (
                    "h_con",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="高度约束（m）"
                    ),
                ),
                (
                    "q_max",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="动压约束（Pa）"
                    ),
                ),
                (
                    "theta_last",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="最终角度约束（°）"
                    ),
                ),
                ("param_name", models.CharField(default="参数变量", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="InitialState",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                ("m_arr", models.CharField(max_length=255, verbose_name="质量数组")),
                ("p_arr", models.CharField(max_length=255, verbose_name="推力数组")),
                ("isp_arr", models.CharField(max_length=255, verbose_name="比冲数组")),
                (
                    "alpha_m",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="转弯段攻角绝对值最大值（°）"
                    ),
                ),
                (
                    "a",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="转弯系数（常数）"
                    ),
                ),
                (
                    "dphi_arr",
                    models.CharField(max_length=255, verbose_name="俯仰角控制系数数组"),
                ),
                ("state_name", models.CharField(default="初始状态", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                ("v_arr", models.CharField(max_length=255, verbose_name="速度数组")),
                ("phi_arr", models.CharField(max_length=255, verbose_name="程序角数组")),
                ("h_arr", models.CharField(max_length=255, verbose_name="高度数组")),
                ("q_arr", models.CharField(max_length=255, verbose_name="动压数组")),
                ("result_name", models.CharField(default="优化结果", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedState",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                (
                    "m1",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第一级质量（kg）"
                    ),
                ),
                (
                    "m2",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第二级质量（kg）"
                    ),
                ),
                (
                    "m3",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第三级质量（kg）"
                    ),
                ),
                (
                    "p1",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第一级推力（kN）"
                    ),
                ),
                (
                    "p2",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第二级推力（kN）"
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="第三级推力（kN）"
                    ),
                ),
                ("isp1", models.IntegerField(verbose_name="第一级燃料比冲（m/s）")),
                ("isp2", models.IntegerField(verbose_name="第二级燃料比冲（m/s）")),
                ("isp3", models.IntegerField(verbose_name="第三级燃料比冲（m/s）")),
                (
                    "alpha_m",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="转弯段攻角绝对值最大值（°）"
                    ),
                ),
                (
                    "a",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="转弯系数（常数）"
                    ),
                ),
                (
                    "d_phi1",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="俯仰角控制系数（°）"
                    ),
                ),
                (
                    "d_phi2",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="俯仰角控制系数（°）"
                    ),
                ),
                ("state_name", models.CharField(default="优化状态", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ParamScope",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                ("m_l_scope", models.CharField(max_length=255, verbose_name="质量下界数组")),
                ("m_u_scope", models.CharField(max_length=255, verbose_name="质量上界数组")),
                ("p_l_scope", models.CharField(max_length=255, verbose_name="质量下界数组")),
                ("p_u_scope", models.CharField(max_length=255, verbose_name="质量上界数组")),
                (
                    "isp_l_scope",
                    models.CharField(max_length=255, verbose_name="比冲下界数组"),
                ),
                ("isp_scope", models.CharField(max_length=255, verbose_name="比冲数组")),
                (
                    "dphi_l_scope",
                    models.CharField(max_length=255, verbose_name="俯仰角控制参数下界数组"),
                ),
                (
                    "dphi_u_scope",
                    models.CharField(max_length=255, verbose_name="俯仰角控制参数上界数组"),
                ),
                (
                    "alpha_m_scope",
                    models.CharField(max_length=255, verbose_name="攻角绝对值最大值数组"),
                ),
                ("a_scope", models.CharField(max_length=255, verbose_name="转弯系数数组")),
                ("scope_name", models.CharField(default="参数范围", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="任务创建时间"
                    ),
                ),
                ("description", models.CharField(max_length=100, verbose_name="任务描述")),
                ("state", models.BooleanField(default=False, verbose_name="任务状态")),
                ("task_name", models.CharField(default="任务", max_length=10)),
            ],
        ),
    ]
