# Generated by Django 4.1.3 on 2022-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_paramscope_isp_l_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="GA",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_id", models.IntegerField(default=0, verbose_name="任务id")),
                ("nind", models.IntegerField(verbose_name="种群规模")),
                ("maxgen", models.IntegerField(verbose_name="进化代数")),
                (
                    "f",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="差分因子"
                    ),
                ),
                (
                    "xovr",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="交叉概率"
                    ),
                ),
                ("ga_name", models.CharField(default="GA模型", max_length=10)),
            ],
        ),
    ]
