# Generated by Django 4.1.3 on 2022-11-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_ga"),
    ]

    operations = [
        migrations.RemoveField(model_name="optimizedstate", name="d_phi1",),
        migrations.RemoveField(model_name="optimizedstate", name="d_phi2",),
        migrations.RemoveField(model_name="optimizedstate", name="isp1",),
        migrations.RemoveField(model_name="optimizedstate", name="isp2",),
        migrations.RemoveField(model_name="optimizedstate", name="isp3",),
        migrations.RemoveField(model_name="optimizedstate", name="m1",),
        migrations.RemoveField(model_name="optimizedstate", name="m2",),
        migrations.RemoveField(model_name="optimizedstate", name="m3",),
        migrations.RemoveField(model_name="optimizedstate", name="p1",),
        migrations.RemoveField(model_name="optimizedstate", name="p2",),
        migrations.RemoveField(model_name="optimizedstate", name="p3",),
        migrations.AddField(
            model_name="optimizedstate",
            name="dphi_arr",
            field=models.CharField(
                default="", max_length=255, verbose_name="俯仰角控制系数数组"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optimizedstate",
            name="isp_arr",
            field=models.CharField(default="", max_length=255, verbose_name="比冲数组"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optimizedstate",
            name="m_arr",
            field=models.CharField(default="", max_length=255, verbose_name="质量数组"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optimizedstate",
            name="p_arr",
            field=models.CharField(default="", max_length=255, verbose_name="推力数组"),
            preserve_default=False,
        ),
    ]
